/**
 * Mock listing metadata. Phase 0 stand-in for RentCast.
 *
 * Every listing carries `source` and `listingUrl` so multi-source aggregation
 * and deep-linking-out are additive later — no schema change required.
 * Intentionally minimal metadata: the app links OUT for the full listing.
 */
import type { Listing } from '../types';

export const MOCK_LISTINGS: Listing[] = [
  // ---- San Francisco ----
  {
    id: 'sf-001',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/san-francisco-ca/mock-sf-001',
    address: '1450 Valencia St',
    neighborhood: 'Mission District',
    city: 'San Francisco',
    lat: 37.7485,
    lng: -122.4204,
    rentMonthly: 3200,
    bedrooms: 1,
    tags: ['pet-friendly', 'in-unit laundry', 'dishwasher'],
    photos: ['/images/apt-loft.jpg'],
    ratingValue: 4.3,
    ratingSource: 'google',
  },
  {
    id: 'sf-002',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/san-francisco-ca/mock-sf-002',
    address: '88 King St',
    neighborhood: 'South Beach',
    city: 'San Francisco',
    lat: 37.7793,
    lng: -122.39,
    rentMonthly: 4100,
    bedrooms: 2,
    tags: ['gym', 'doorman', 'parking', 'in-unit laundry'],
    photos: ['/images/apt-penthouse.jpg'],
    ratingValue: 4.6,
    ratingSource: 'aggregated',
  },
  {
    id: 'sf-003',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/san-francisco-ca/mock-sf-003',
    address: '601 Van Ness Ave',
    neighborhood: 'Hayes Valley',
    city: 'San Francisco',
    lat: 37.7825,
    lng: -122.4205,
    rentMonthly: 2750,
    bedrooms: 0,
    tags: ['rooftop', 'transit-friendly'],
    ratingValue: null,
    ratingSource: 'aggregated',
  },
  {
    id: 'sf-004',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/san-francisco-ca/mock-sf-004',
    address: '2200 Sacramento St',
    neighborhood: 'Pacific Heights',
    city: 'San Francisco',
    lat: 37.7915,
    lng: -122.4324,
    rentMonthly: 5200,
    bedrooms: 3,
    tags: ['parking', 'in-unit laundry', 'dishwasher', 'hardwood floors'],
    photos: ['/images/apt-studio.jpg'],
    ratingValue: 4.1,
    ratingSource: 'google',
  },
  {
    id: 'sf-005',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/san-francisco-ca/mock-sf-005',
    address: '1 Folsom St',
    neighborhood: 'Embarcadero',
    city: 'San Francisco',
    lat: 37.7913,
    lng: -122.3899,
    rentMonthly: 3650,
    bedrooms: 1,
    tags: ['gym', 'pool', 'doorman', 'bay views'],
    ratingValue: 3.8,
    ratingSource: 'google',
  },

  // ---- New York ----
  {
    id: 'ny-001',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/new-york-ny/mock-ny-001',
    address: '250 Bedford Ave',
    neighborhood: 'Williamsburg',
    city: 'New York',
    lat: 40.7142,
    lng: -73.9614,
    rentMonthly: 3400,
    bedrooms: 1,
    tags: ['pet-friendly', 'rooftop', 'transit-friendly'],
    photos: ['/images/skyline-river.jpg'],
    ratingValue: 4.4,
    ratingSource: 'aggregated',
  },
  {
    id: 'ny-002',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/new-york-ny/mock-ny-002',
    address: '15 W 81st St',
    neighborhood: 'Upper West Side',
    city: 'New York',
    lat: 40.7847,
    lng: -73.9737,
    rentMonthly: 4500,
    bedrooms: 2,
    tags: ['doorman', 'elevator', 'park views'],
    ratingValue: 4.2,
    ratingSource: 'google',
  },
  {
    id: 'ny-003',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/new-york-ny/mock-ny-003',
    address: '88 Greenwich St',
    neighborhood: 'Financial District',
    city: 'New York',
    lat: 40.7075,
    lng: -74.0134,
    rentMonthly: 3900,
    bedrooms: 1,
    tags: ['gym', 'in-unit laundry', 'doorman'],
    ratingValue: null,
    ratingSource: 'aggregated',
  },
  {
    id: 'ny-004',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/new-york-ny/mock-ny-004',
    address: '500 W 30th St',
    neighborhood: 'Chelsea',
    city: 'New York',
    lat: 40.752,
    lng: -74.0027,
    rentMonthly: 5600,
    bedrooms: 2,
    tags: ['gym', 'pool', 'doorman', 'in-unit laundry'],
    photos: ['/images/hero-skyline.jpg'],
    ratingValue: 4.7,
    ratingSource: 'aggregated',
  },

  // ---- Austin ----
  {
    id: 'atx-001',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/austin-tx/mock-atx-001',
    address: '1801 E 6th St',
    neighborhood: 'East Austin',
    city: 'Austin',
    lat: 30.2627,
    lng: -97.7203,
    rentMonthly: 1850,
    bedrooms: 1,
    tags: ['pet-friendly', 'parking', 'patio'],
    photos: ['/images/apt-loft.jpg'],
    ratingValue: 4.5,
    ratingSource: 'google',
  },
  {
    id: 'atx-002',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/austin-tx/mock-atx-002',
    address: '54 Rainey St',
    neighborhood: 'Rainey Street',
    city: 'Austin',
    lat: 30.2592,
    lng: -97.7394,
    rentMonthly: 2600,
    bedrooms: 2,
    tags: ['gym', 'pool', 'rooftop', 'in-unit laundry'],
    photos: ['/images/apt-penthouse.jpg'],
    ratingValue: 4.0,
    ratingSource: 'aggregated',
  },
  {
    id: 'atx-003',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/austin-tx/mock-atx-003',
    address: '3800 N Lamar Blvd',
    neighborhood: 'Hyde Park',
    city: 'Austin',
    lat: 30.3068,
    lng: -97.7385,
    rentMonthly: 1500,
    bedrooms: 0,
    tags: ['parking', 'transit-friendly'],
    ratingValue: 3.6,
    ratingSource: 'google',
  },

  // ---- Boston ----
  {
    id: 'bos-001',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/boston-ma/mock-bos-001',
    address: '360 Newbury St',
    neighborhood: 'Back Bay',
    city: 'Boston',
    lat: 42.3503,
    lng: -71.081,
    rentMonthly: 3100,
    bedrooms: 1,
    tags: ['in-unit laundry', 'hardwood floors', 'pet-friendly'],
    ratingValue: 4.4,
    ratingSource: 'google',
    photos: ['/images/skyline-river.jpg'],
  },
  {
    id: 'bos-002',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/boston-ma/mock-bos-002',
    address: '540 Tremont St',
    neighborhood: 'South End',
    city: 'Boston',
    lat: 42.3388,
    lng: -71.0765,
    rentMonthly: 3900,
    bedrooms: 2,
    tags: ['parking', 'dishwasher', 'hardwood floors'],
    ratingValue: 4.2,
    ratingSource: 'aggregated',
  },
  {
    id: 'bos-003',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/boston-ma/mock-bos-003',
    address: '250 Third St',
    neighborhood: 'Kendall Square',
    city: 'Boston',
    lat: 42.3626,
    lng: -71.0843,
    rentMonthly: 2400,
    bedrooms: 0,
    tags: ['transit-friendly', 'gym'],
    ratingValue: null,
    ratingSource: 'aggregated',
    photos: ['/images/brooklyn-bridge.jpg'],
  },
  {
    id: 'bos-004',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/boston-ma/mock-bos-004',
    address: '100 Seaport Blvd',
    neighborhood: 'Seaport',
    city: 'Boston',
    lat: 42.3519,
    lng: -71.0448,
    rentMonthly: 3600,
    bedrooms: 1,
    tags: ['gym', 'doorman', 'rooftop', 'in-unit laundry'],
    ratingValue: 4.6,
    ratingSource: 'aggregated',
    photos: ['/images/apt-loft.jpg'],
  },
  {
    id: 'bos-005',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/boston-ma/mock-bos-005',
    address: '15 Green St',
    neighborhood: 'Jamaica Plain',
    city: 'Boston',
    lat: 42.3098,
    lng: -71.1147,
    rentMonthly: 2800,
    bedrooms: 2,
    tags: ['pet-friendly', 'parking', 'patio'],
    ratingValue: 4.0,
    ratingSource: 'google',
  },

  // ---- Chicago ----
  {
    id: 'chi-001',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/chicago-il/mock-chi-001',
    address: '1000 W Washington Blvd',
    neighborhood: 'West Loop',
    city: 'Chicago',
    lat: 41.8827,
    lng: -87.6494,
    rentMonthly: 2400,
    bedrooms: 1,
    tags: ['gym', 'rooftop', 'in-unit laundry'],
    ratingValue: 4.5,
    ratingSource: 'aggregated',
    photos: ['/images/apt-penthouse.jpg'],
  },
  {
    id: 'chi-002',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/chicago-il/mock-chi-002',
    address: '2100 N Clark St',
    neighborhood: 'Lincoln Park',
    city: 'Chicago',
    lat: 41.9214,
    lng: -87.6513,
    rentMonthly: 2900,
    bedrooms: 2,
    tags: ['pet-friendly', 'parking', 'dishwasher'],
    ratingValue: 4.3,
    ratingSource: 'google',
  },
  {
    id: 'chi-003',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/chicago-il/mock-chi-003',
    address: '1450 N Milwaukee Ave',
    neighborhood: 'Wicker Park',
    city: 'Chicago',
    lat: 41.9088,
    lng: -87.6796,
    rentMonthly: 1600,
    bedrooms: 0,
    tags: ['transit-friendly', 'hardwood floors'],
    ratingValue: 4.1,
    ratingSource: 'aggregated',
    photos: ['/images/apt-studio.jpg'],
  },
  {
    id: 'chi-004',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/chicago-il/mock-chi-004',
    address: '400 W Ontario St',
    neighborhood: 'River North',
    city: 'Chicago',
    lat: 41.8925,
    lng: -87.634,
    rentMonthly: 2600,
    bedrooms: 1,
    tags: ['doorman', 'gym', 'pool', 'lake views'],
    ratingValue: 4.4,
    ratingSource: 'aggregated',
  },
  {
    id: 'chi-005',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/chicago-il/mock-chi-005',
    address: '5300 S Hyde Park Blvd',
    neighborhood: 'Hyde Park',
    city: 'Chicago',
    lat: 41.7943,
    lng: -87.5907,
    rentMonthly: 1900,
    bedrooms: 2,
    tags: ['parking', 'transit-friendly'],
    ratingValue: null,
    ratingSource: 'google',
    photos: ['/images/hero-skyline.jpg'],
  },

  // ---- Seattle ----
  {
    id: 'sea-001',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/seattle-wa/mock-sea-001',
    address: '1620 Broadway',
    neighborhood: 'Capitol Hill',
    city: 'Seattle',
    lat: 47.6253,
    lng: -122.3222,
    rentMonthly: 2300,
    bedrooms: 1,
    tags: ['pet-friendly', 'in-unit laundry', 'rooftop'],
    ratingValue: 4.3,
    ratingSource: 'google',
    photos: ['/images/skyline-river.jpg'],
  },
  {
    id: 'sea-002',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/seattle-wa/mock-sea-002',
    address: '300 Terry Ave N',
    neighborhood: 'South Lake Union',
    city: 'Seattle',
    lat: 47.627,
    lng: -122.337,
    rentMonthly: 3400,
    bedrooms: 2,
    tags: ['gym', 'doorman', 'parking', 'in-unit laundry'],
    ratingValue: 4.6,
    ratingSource: 'aggregated',
  },
  {
    id: 'sea-003',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/seattle-wa/mock-sea-003',
    address: '5400 Ballard Ave NW',
    neighborhood: 'Ballard',
    city: 'Seattle',
    lat: 47.6685,
    lng: -122.3841,
    rentMonthly: 1700,
    bedrooms: 0,
    tags: ['transit-friendly', 'patio'],
    ratingValue: 3.9,
    ratingSource: 'aggregated',
    photos: ['/images/brooklyn-bridge.jpg'],
  },
  {
    id: 'sea-004',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/seattle-wa/mock-sea-004',
    address: '2600 First Ave',
    neighborhood: 'Belltown',
    city: 'Seattle',
    lat: 47.6145,
    lng: -122.3489,
    rentMonthly: 2500,
    bedrooms: 1,
    tags: ['gym', 'pool', 'bay views'],
    ratingValue: 4.2,
    ratingSource: 'google',
  },

  // ---- Los Angeles ----
  {
    id: 'la-001',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/los-angeles-ca/mock-la-001',
    address: '2700 Sunset Blvd',
    neighborhood: 'Silver Lake',
    city: 'Los Angeles',
    lat: 34.0869,
    lng: -118.2702,
    rentMonthly: 2600,
    bedrooms: 1,
    tags: ['pet-friendly', 'hardwood floors', 'patio'],
    ratingValue: 4.2,
    ratingSource: 'google',
    photos: ['/images/skyline-river.jpg'],
  },
  {
    id: 'la-002',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/los-angeles-ca/mock-la-002',
    address: '800 W Olympic Blvd',
    neighborhood: 'Downtown LA',
    city: 'Los Angeles',
    lat: 34.0407,
    lng: -118.2468,
    rentMonthly: 3300,
    bedrooms: 2,
    tags: ['gym', 'pool', 'doorman', 'rooftop'],
    ratingValue: 4.4,
    ratingSource: 'aggregated',
  },
  {
    id: 'la-003',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/los-angeles-ca/mock-la-003',
    address: '1315 Ocean Ave',
    neighborhood: 'Santa Monica',
    city: 'Los Angeles',
    lat: 34.0195,
    lng: -118.4912,
    rentMonthly: 3500,
    bedrooms: 1,
    tags: ['parking', 'in-unit laundry', 'bay views'],
    ratingValue: 4.5,
    ratingSource: 'google',
    photos: ['/images/brooklyn-bridge.jpg'],
  },
  {
    id: 'la-004',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/los-angeles-ca/mock-la-004',
    address: '3400 W 6th St',
    neighborhood: 'Koreatown',
    city: 'Los Angeles',
    lat: 34.0619,
    lng: -118.3005,
    rentMonthly: 1500,
    bedrooms: 0,
    tags: ['transit-friendly', 'gym'],
    ratingValue: null,
    ratingSource: 'aggregated',
  },
];
