/**
 * Mock listing metadata. Phase 0 stand-in for RentCast.
 *
 * Every listing carries `source` and `listingUrl` so multi-source aggregation
 * and deep-linking-out are additive later — no schema change required.
 * Intentionally minimal metadata: the app links OUT for the full listing.
 */
import type { Listing } from '../types';

export const MOCK_LISTINGS: Listing[] = [
  // ---- San Francisco ----
  {
    id: 'sf-001',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/san-francisco-ca/mock-sf-001',
    address: '1450 Valencia St',
    neighborhood: 'Mission District',
    city: 'San Francisco',
    lat: 37.7485,
    lng: -122.4204,
    rentMonthly: 3200,
    bedrooms: 1,
    tags: ['pet-friendly', 'in-unit laundry', 'dishwasher'],
    ratingValue: 4.3,
    ratingSource: 'google',
  },
  {
    id: 'sf-002',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/san-francisco-ca/mock-sf-002',
    address: '88 King St',
    neighborhood: 'South Beach',
    city: 'San Francisco',
    lat: 37.7793,
    lng: -122.39,
    rentMonthly: 4100,
    bedrooms: 2,
    tags: ['gym', 'doorman', 'parking', 'in-unit laundry'],
    ratingValue: 4.6,
    ratingSource: 'aggregated',
  },
  {
    id: 'sf-003',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/san-francisco-ca/mock-sf-003',
    address: '601 Van Ness Ave',
    neighborhood: 'Hayes Valley',
    city: 'San Francisco',
    lat: 37.7825,
    lng: -122.4205,
    rentMonthly: 2750,
    bedrooms: 0,
    tags: ['rooftop', 'transit-friendly'],
    ratingValue: null,
    ratingSource: 'aggregated',
  },
  {
    id: 'sf-004',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/san-francisco-ca/mock-sf-004',
    address: '2200 Sacramento St',
    neighborhood: 'Pacific Heights',
    city: 'San Francisco',
    lat: 37.7915,
    lng: -122.4324,
    rentMonthly: 5200,
    bedrooms: 3,
    tags: ['parking', 'in-unit laundry', 'dishwasher', 'hardwood floors'],
    ratingValue: 4.1,
    ratingSource: 'google',
  },
  {
    id: 'sf-005',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/san-francisco-ca/mock-sf-005',
    address: '1 Folsom St',
    neighborhood: 'Embarcadero',
    city: 'San Francisco',
    lat: 37.7913,
    lng: -122.3899,
    rentMonthly: 3650,
    bedrooms: 1,
    tags: ['gym', 'pool', 'doorman', 'bay views'],
    ratingValue: 3.8,
    ratingSource: 'google',
  },

  // ---- New York ----
  {
    id: 'ny-001',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/new-york-ny/mock-ny-001',
    address: '250 Bedford Ave',
    neighborhood: 'Williamsburg',
    city: 'New York',
    lat: 40.7142,
    lng: -73.9614,
    rentMonthly: 3400,
    bedrooms: 1,
    tags: ['pet-friendly', 'rooftop', 'transit-friendly'],
    ratingValue: 4.4,
    ratingSource: 'aggregated',
  },
  {
    id: 'ny-002',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/new-york-ny/mock-ny-002',
    address: '15 W 81st St',
    neighborhood: 'Upper West Side',
    city: 'New York',
    lat: 40.7847,
    lng: -73.9737,
    rentMonthly: 4500,
    bedrooms: 2,
    tags: ['doorman', 'elevator', 'park views'],
    ratingValue: 4.2,
    ratingSource: 'google',
  },
  {
    id: 'ny-003',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/new-york-ny/mock-ny-003',
    address: '88 Greenwich St',
    neighborhood: 'Financial District',
    city: 'New York',
    lat: 40.7075,
    lng: -74.0134,
    rentMonthly: 3900,
    bedrooms: 1,
    tags: ['gym', 'in-unit laundry', 'doorman'],
    ratingValue: null,
    ratingSource: 'aggregated',
  },
  {
    id: 'ny-004',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/new-york-ny/mock-ny-004',
    address: '500 W 30th St',
    neighborhood: 'Chelsea',
    city: 'New York',
    lat: 40.752,
    lng: -74.0027,
    rentMonthly: 5600,
    bedrooms: 2,
    tags: ['gym', 'pool', 'doorman', 'in-unit laundry'],
    ratingValue: 4.7,
    ratingSource: 'aggregated',
  },

  // ---- Austin ----
  {
    id: 'atx-001',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/austin-tx/mock-atx-001',
    address: '1801 E 6th St',
    neighborhood: 'East Austin',
    city: 'Austin',
    lat: 30.2627,
    lng: -97.7203,
    rentMonthly: 1850,
    bedrooms: 1,
    tags: ['pet-friendly', 'parking', 'patio'],
    ratingValue: 4.5,
    ratingSource: 'google',
  },
  {
    id: 'atx-002',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/austin-tx/mock-atx-002',
    address: '54 Rainey St',
    neighborhood: 'Rainey Street',
    city: 'Austin',
    lat: 30.2592,
    lng: -97.7394,
    rentMonthly: 2600,
    bedrooms: 2,
    tags: ['gym', 'pool', 'rooftop', 'in-unit laundry'],
    ratingValue: 4.0,
    ratingSource: 'aggregated',
  },
  {
    id: 'atx-003',
    source: 'mock',
    listingUrl: 'https://www.apartments.com/austin-tx/mock-atx-003',
    address: '3800 N Lamar Blvd',
    neighborhood: 'Hyde Park',
    city: 'Austin',
    lat: 30.3068,
    lng: -97.7385,
    rentMonthly: 1500,
    bedrooms: 0,
    tags: ['parking', 'transit-friendly'],
    ratingValue: 3.6,
    ratingSource: 'google',
  },
];
